[project]
name = "galaxychop"
version = "0.3.dev0"
authors = [
    { name = "Valeria Cristiani et al", email = "valeria.cristiani@unc.edu.ar" },
    { name = "Juan B Cabral", email = "jbcabral@unc.edu.ar" },
]
readme = "README.md"
license = { file = "LICENSE.txt" }
description = "Galaxy dynamic de-composition"
keywords = ["galaxy", "dynamics"]
requires-python = ">=3.11,<3.16"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
]

urls = { "Homepage" = "https://github.com/vcristiani/galaxy-chop", "Repository" = "https://github.com/vcristiani/galaxy-chop" }

dependencies = [
    # --- Core ---
    "scipy >= 1.0",
    "scikit-learn",
    "uttrs",
    "h5py",
    "custom_inherit",
    "grispy",
    "joblib",
    "typer >= 0.9.0",

    # --- Astropy ---
    "astropy >= 6",

    # --- Seaborn y matplotlib ---
    "seaborn >= 0.12",
    "matplotlib >= 3.8",

    # --- Numpy ---
    "numpy >= 2.0",

    # --- Pandas ---
    "pandas >= 2.0",

    # --- Numba ---
    "numba >= 0.59",
]

[project.scripts]
galaxychop = "galaxychop.cli:main"



[tool.black]
line-length = 79
target-version = ["py311", "py312", "py313"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "plot: marks tests as part of the integration with matplotlib slow (deselect with '-m \"not plots\"')",
    "model: marks tests as part model decomposition API (deselect with '-m \"not model\"')",
]
testpaths = ["tests"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["galaxychop", "galaxychop.*"]
namespaces = false

[tool.basedpyright]
reportUnknownVariableType = false
reportMissingParameterType = false

[tool.pyright]
reportMissingParameterType = false
